In [1]:
import pandas as pd

# Datos en formato diccionario
datos = {
    "Nombre": ["Lucía", "Carlos", "María", "David", "Ana", "Pepe", "Pepe"],
    "Edad": [28, 35, 22, 41, 30, 18, 18],
    "Sexo": ["F", "M", "F", "M", "F", "M", "M"],
    "Ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao", "Badajoz", "Badajoz"],
    "Salario": [32000, 45000, 29000, 51000, 38000, 27000, 27000]
}

# Crear DataFrame
df = pd.DataFrame(datos)

In [2]:
# Guardar como CSV
df.to_csv("datos.csv", index=False)

In [3]:
df = pd.read_csv("datos.csv")
print(df)

   Nombre  Edad Sexo     Ciudad  Salario
0   Lucía    28    F     Madrid    32000
1  Carlos    35    M  Barcelona    45000
2   María    22    F   Valencia    29000
3   David    41    M    Sevilla    51000
4     Ana    30    F     Bilbao    38000
5    Pepe    18    M    Badajoz    27000
6    Pepe    18    M    Badajoz    27000

In [4]:
# Revisar duplicados y eliminarlos si hay
print(f'Duplicados: {df.duplicated().sum()}')
df.drop_duplicates(inplace=True) #inplace es para sustituir directamente en el mismo objeto df

Duplicados: 1

In [5]:
df

   Nombre  Edad Sexo     Ciudad  Salario
0   Lucía    28    F     Madrid    32000
1  Carlos    35    M  Barcelona    45000
2   María    22    F   Valencia    29000
3   David    41    M    Sevilla    51000
4     Ana    30    F     Bilbao    38000
5    Pepe    18    M    Badajoz    27000

In [6]:
print(df)

   Nombre  Edad Sexo     Ciudad  Salario
0   Lucía    28    F     Madrid    32000
1  Carlos    35    M  Barcelona    45000
2   María    22    F   Valencia    29000
3   David    41    M    Sevilla    51000
4     Ana    30    F     Bilbao    38000
5    Pepe    18    M    Badajoz    27000

In [7]:
#Cargar dataset
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")

In [8]:
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [9]:
# 1. Revisar info y valores nulos
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None

In [10]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [11]:
# 2. Imputar o eliminar valores nulos
# Edad (age) tiene valores nulos, imputamos con la mediana
df['age'].fillna(df['age'].median(), inplace=True) #inplace es para sustituir directamente en el mismo objeto df

/tmp/ipykernel_42761/2443989211.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True) #inplace es para sustituir directamente en el mismo objeto df

In [12]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [13]:
# Embarked tiene pocos nulos, imputamos con la moda
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True) #Ponemos el primer valor de la serie moda

/tmp/ipykernel_42761/2949824484.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0], inplace=True) #Ponemos el primer valor de la serie moda

In [14]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [15]:
# 3. Eliminar columnas poco útiles, redundantes o con muchos valores nulos
df.drop(columns=['deck', 'alive', 'class', 'who', 'adult_male', 'embark_town', 'alone'], inplace=True)

In [16]:
print(df.isnull().sum())

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [17]:
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [18]:
# 4. Convertir variables categóricas a numéricas con LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in ['sex', 'embarked']:
    df[col] = le.fit_transform(df[col])

In [19]:
df

     survived  pclass  sex   age  sibsp  parch     fare  embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0  28.0      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

In [20]:
from sklearn.preprocessing import MinMaxScaler
# Paso 1: Dividir X e y
X = df.drop('survived', axis=1)
y = df['survived']

In [21]:

X

     pclass  sex   age  sibsp  parch     fare  embarked
0         3    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         3    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         3    1  35.0      0      0   8.0500         2
..      ...  ...   ...    ...    ...      ...       ...
886       2    1  27.0      0      0  13.0000         2
887       1    0  19.0      0      0  30.0000         2
888       3    0  28.0      1      2  23.4500         2
889       1    1  26.0      0      0  30.0000         0
890       3    1  32.0      0      0   7.7500         1

[891 rows x 7 columns]

In [22]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [23]:
# Paso 2: Normalizar X con MinMaxScaler
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

In [24]:
# Paso 3: Convertir a DataFrame para facilitar lectura
X_normalized_df = pd.DataFrame(X_normalized, columns=X.columns)

In [25]:
print("\nDatos normalizados (primeras filas):\n", X_normalized_df.head())
print("\nVariable objetivo (y):\n", y.head())

Datos normalizados (primeras filas):
    pclass  sex       age  sibsp  parch      fare  embarked
0     1.0  1.0  0.271174  0.125    0.0  0.014151       1.0
1     0.0  0.0  0.472229  0.125    0.0  0.139136       0.0
2     1.0  0.0  0.321438  0.000    0.0  0.015469       1.0
3     0.0  0.0  0.434531  0.125    0.0  0.103644       1.0
4     1.0  1.0  0.434531  0.000    0.0  0.015713       1.0

Variable objetivo (y):
 0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64